name: Data Pipeline

on:
  workflow_dispatch:
    inputs:
      date:
        type: string
        description: 'The date to run on'
        default: ''
      branch:
        description: 'The branch to run on'
        required: true
        default: 'main'
        type: string
  schedule:
    # Run every Thursday morning at midnight
    - cron: '0 0 * * 4'

jobs:
  get-data-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to commit changes
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DATA_PIPELINE_PR_AUTOMATION_KEY }}
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run data-fetching script PL
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: npm run get-data -- PL ${{ inputs.date }}

      - name: Run data-fetching script CL
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: npm run get-data -- CL ${{ inputs.date }}


      - name: Log changes
        run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: automated data update"
          branch: "data-update"
          base: "main"
          title: "Fixture Data Update"
          body: |
            This is an automated pull request created by GitHub Actions.
            Should only collect `src/content/fixtures/*`
          labels: |
            data-pipeline-update
          # The GitHub API does not allow creating a PR and
          # adding labels in a single request.
          # The peter-evans/create-pull-request
          # action handles this by creating the PR first,
          # and then immediately making a separate API call
          # to add the labels.This is relevant if you have another
          # workflow that is immediately triggered by the PR creation
          # and checks for those labels. Occasionally, the label-checking
          # workflow might start before the labels are fully applied,
          # causing a race condition. If this happens, you might need to
          # add a small delay or change the trigger for the downstream
          # workflow to on: pull_request: types: [labeled].
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
